package e.e.a;
import org.json.*;import java.nio.file.*;import android.content.Context;import android.widget.*;import android.view.View;
public class PaidVideosTest {
static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
static JSONObject find(Object x,String id){if(x instanceof JSONObject){JSONObject o=(JSONObject)x;if(id.equals(o.optString("id")))return o;for(String k:o.keySet()){JSONObject r=find(o.opt(k),id);if(r!=null)return r;}}else if(x instanceof JSONArray){JSONArray a=(JSONArray)x;for(int i=0;i<a.length();i++){JSONObject r=find(a.opt(i),id);if(r!=null)return r;}}return null;}
static double luminance(int c){double sum=0;double[] weights={.2126,.7152,.0722};for(int i=0;i<3;i++){double n=(c>>(16-8*i)&255)/255.;sum+=weights[i]*(n<=.04045?n/12.92:Math.pow((n+.055)/1.055,2.4));}return sum;}
public static void main(String[] args)throws Exception{
JSONObject search=new JSONObject(new String(Files.readAllBytes(Paths.get(args[0])),"UTF-8"));JSONObject sample=find(search,"so46872835");check(sample!=null&&sample.getBoolean("isPaymentRequired"),"actual list metadata");PaidVideos.remember(sample);check(PaidVideos.required("https://www.nicovideo.jp/watch/so46872835?from=search"),"actual paid example");
check(!PaidVideos.required("so12345"),"channel prefix alone never implies paid");PaidVideos.remember(new JSONObject().put("id","so12345").put("isChannelVideo",true).put("isPaymentRequired",false));check(!PaidVideos.required("so12345"),"free channel video remains free");PaidVideos.remember(new JSONObject().put("id","so12345").put("isPaymentRequired",true));check(PaidVideos.required("so12345"),"current paid flag used");PaidVideos.remember(new JSONObject().put("id","so12345").put("isPaymentRequired",false));check(!PaidVideos.required("so12345"),"new free flag removes stale paid metadata");
JSONObject watch=new JSONObject(new String(Files.readAllBytes(Paths.get(args[1])),"UTF-8")).getJSONObject("data").getJSONObject("response").getJSONObject("data");check(PaidVideos.watchRequired(watch),"member-only example payment metadata");check(!PaidVideos.watchRequired(new JSONObject()),"missing metadata remains unknown/free");
for(int color:new int[]{0xff31c7b1,0xffb2c6ff,0xff48652d,0xffb2d18b}){Context c=new Context();c.theme.accent=color;RelativeLayout thumb=new RelativeLayout(c);PaidVideos.show(thumb,true);check(thumb.children.size()==1,"single badge");TextView b=(TextView)thumb.children.get(0);check(b.bg==color,"actual view theme accent");double a=luminance(b.bg),d=luminance(b.fg);check((Math.max(a,d)+.05)/(Math.min(a,d)+.05)>=4.5,"readable badge contrast");PaidVideos.show(thumb,false);check(b.visibility==View.GONE,"reused free row clears badge");PaidVideos.show(thumb,true);check(thumb.children.size()==1&&b.visibility==View.VISIBLE,"reused paid row restores badge");}
UiStrings.selectLanguage("1");check(UiStrings.translate("有料").equals("Paid"),"English");UiStrings.selectLanguage("2");check(UiStrings.translate("有料").equals("付費"),"Traditional Chinese");UiStrings.selectLanguage("0");check(UiStrings.translate("有料").equals("有料"),"Japanese");
System.out.println("Actual paid list/watch metadata, free channel distinction, updates, badge reuse, four theme contrasts and translations verified");}}
